spring:
  application:
    name : SchoolManagementSystem
  data:
    mongodb:
      database: studentSystem
      uri : mongodb link
jwt:
  secret: "TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V"
  expiration: 3000000

email: ^[a-zA-Z0-9._%+-]+@gmail\.com$

logging:
  level:
      org.springframework: DEBUG
      org.springframework.beans: DEBUG
      org.springframework.security: DEBUG
